name: "Validate SAST DEP"
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11,14,15,16]
        distribution: ['zulu']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }} Distribution ${{ matrix.distribution }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: test with Gradle
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build
      - name: generateLicenseReport with Gradle
        run: ./gradlew generateLicenseReport
      #- name: dependencyCheckAnalyze with Gradle
      #  run: ./gradlew dependencyCheckAnalyze
      - uses: actions/upload-artifact@v1
        with:
          name: licenseDependencyReport
          path: build/reports
      - uses: gradle/wrapper-validation-action@v1
      - name: Self dep-scan
        uses: AppThreat/dep-scan-action@master
        env:
          VULNDB_HOME: ${{ github.workspace }}/db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}:[]
      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports 
       
     
         
